name: Deployment
on:
  push:
    branches:
      - master
      - dev
env:
  MONGODB_DB_NAME: 'give database name here'
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    env:
      MONGODB_CLUSTER_ADDRESS: 'give cluster address here'
      MONGODB_USERNAME: 'give username here'
      MONGODB_PASSWORD: 'give password here'
      PORT: XYZ
    steps:
      - name: Get Code
        uses: actions/checkout@v
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        run: echo "MongoDB Username -> $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "MongoDB Name -> ${{ env.MONGODB_DB_NAME}}"
